object Modules {
    const val SHARED_UI = ":shared-ui"
    const val CORE = ":core"
    const val NETWORK = ":network"
    const val NAVIGATION = ":navigation"
    const val AUTH = ":features:auth"
    const val MOVIES = ":features:movies"
    const val SEARCH = ":features:search"
    const val SHOWS = ":features:shows"
    const val PEOPLE = ":features:people"
    const val TRENDING = ":features:trending"
    const val SETTINGS = ":features:settings"
    const val REVIEWS = ":features:reviews"
    const val PREFS = ":prefs"
    const val SHARED = ":shared"
    const val DOMAIN = ":domain"
}